ResourceNotFoundException.user.message=There is no user with reference [{0}].
ResourceNotFoundException.repository.message=There is no repository with reference [{0}].
ResourceNotFoundException.workspace.message=There is no workspace with reference [{0}].
ResourceNotFoundException.translation-locale.message=There is no translation locale with reference [{0}].
ResourceNotFoundException.translation.message=There is no translation with reference [{0}].

BadRequestException.action-not-supported.message=The action [{0}] is not supported.
BadRequestException.start-review-no-message.message=There is no message specify. A message is needed when starting a review.
BadRequestException.id-request-id-body-not-match.message=The id [{0}] does not match the id in the body [{1}].

RepositoryException.open.message=Error while opening the repository.
RepositoryException.update.message=Error while updating the local repository.
RepositoryException.delete.message=Error while updating the deleting repository.
RepositoryException.branch-not-found.message=The branch [{0}] does not exist.
RepositoryException.branch-list.message=Error while listing branches.
RepositoryException.branch-creation.message=Error while creating branch [{0}].
RepositoryException.branch-already-exist.message=The branch [{0}] already exists.
RepositoryException.branch-deletion.message=Error while deleting branch [{0}].
RepositoryException.branch-switching.message=Error while switching to the branch [{0}].
RepositoryException.pushing.message=Error while pushing changes.
RepositoryException.reverting.message=Error while reverting changes.
RepositoryException.forbidden-branch-deletion.message=Cannot delete branch [{0}].
RepositoryException.locking-timeout.message=Error while trying to get the lock on the repository.

InternalException.message=An internal issue occurred. If this issue still happens, please contact the support.
